name: Delete npm package

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Enter release version want to delete'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Delete npm packages
        uses: meta205/actions-delete-package@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          package-name: wingui,wingui-core
          package-version: ${{ inputs.release-version }}
          package-type: npm
          owner: zionex
