name: Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: 'Select release type'
        options:
          - TEST
          - RELEASE

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: echo ${{ inputs.release-type }}
      - name: Echo conditionally
        if: ${{ inputs.release-type == 'TEST' }}
        run: echo "${{ inputs.release-type }} option"
      - name: Echo conditionally
        if: ${{ inputs.release-type == 'RELEASE' }}
        run: echo "${{ inputs.release-type }} option"
