name: Sandbox

on:
  workflow_dispatch:
    inputs:
      ui-corp-kr:
        type: boolean
        required: false
        description: 'KR'
        default: false
      ui-corp-vn:
        type: boolean
        required: false
        description: 'VN'
        default: false
      ui-env:
        type: choice
        required: true
        description: 'Select Wingui environment'
        options:
          - dev
          - qc
          - prod

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      working-directory-config: './config'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up yq
        run: |
          mkdir -p $HOME/.local/bin
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          wget -qO $HOME/.local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod a+x $HOME/.local/bin/yq
      - name: Set mp server max memory
        working-directory: ${{ env.working-directory-config }}
        run: |
          echo "kr=$(yq '.memory.kr.${{ inputs.ui-env }}' application.yaml)" >> $GITHUB_OUTPUT
          echo "vn=$(yq '.memory.vn.${{ inputs.ui-env }}' application.yaml)" >> $GITHUB_OUTPUT
        id: memory
      - name: Check yq result
        run: |
          echo ${{ steps.memory.outputs.kr }}
          echo ${{ steps.memory.outputs.vn }}
      - name: Create yajsw files - KR
        uses: zionex/actions-yajsw@v1
        with:
          dist-path: './release'
          service-name: 'TEST'
          java-app-jar-file: 'TEST.jar'
          java-max-memory: ${{ steps.memory.outputs.kr }}
      - name: Check yq result
        run: |
          cd release
          ls -al
          cd wrapper
          ls -al
          cd conf
          echo wrapper.conf
      - name: Create yajsw files - VN
        uses: zionex/actions-yajsw@v1
        with:
          dist-path: './release'
          service-name: 'TEST'
          java-app-jar-file: 'TEST.jar'
          java-max-memory: ${{ steps.memory.outputs.vn }}
      - name: Check yq result
        run: |
          cd release
          ls -al
          cd wrapper
          ls -al
          cd conf
          echo wrapper.conf
