name: Sandbox

on:
  workflow_dispatch:
    inputs:
      WingUI:
        type: boolean
        required: false
        description: 'WingUI'
        default: true
      MP:
        type: boolean
        required: false
        description: 'MP'
        default: false
      BaseServer:
        type: boolean
        required: false
        description: 'BaseServer'
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: echo 1234
  exception:
    if: ${{ failure() }}
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: echo 1234
  notification:
    if: ${{ always() }}
    needs: [release, exception]
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: echo 1234
          
