name: Sandbox

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        if: ${{ inputs.release-type == 'RELEASE' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.ZIONEX_CI_MAIL_USERNAME }}
          password: ${{ secrets.ZIONEX_CI_MAIL_PASSWORD }}
          subject: "GitHub Action Sending Mail Test"
          to: hoonrho_lee@zionex.com
          from: Zionex Release
          body: This is test
