name: Sandbox

on:
  workflow_dispatch:
    WingUI:
      type: boolean
      required: false
      description: 'WingUI'
      default: true
    MP:
      type: boolean
      required: false
      description: 'MP'
      default: true
    BaseServer:
      type: boolean
      required: false
      description: 'BaseServer'
      default: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Run if WingUI is true
        if: ${{ inputs.WingUI == 'true' }}
        id: use-output
        run: echo $WingUI
      - name: Run if MP is true
        if: ${{ inputs.MP == 'true' }}
        id: use-output
        run: echo $MP
      - name: Run if BaseServer is true
        if: ${{ inputs.BaseServer == 'true' }}
        id: use-output
        run: echo $BaseServer
